### ISSUE TITLE
ImportError: cannot import name '_PosixFlavour' from 'pathlib'

### ISSUE THREAD

**Issue by anki-code** [juftin/browsr#43]
```xsh
docker run -it --rm python:3.12-slim bash
pip install browsr
# browsr 1.19.0
browsr .
```

```xsh
Traceback (most recent call last):
  File "/usr/local/bin/browsr", line 5, in <module>
    from browsr.__main__ import browsr
  File "/usr/local/lib/python3.12/site-packages/browsr/__main__.py", line 5, in <module>
    from browsr.cli import browsr
  File "/usr/local/lib/python3.12/site-packages/browsr/cli.py", line 12, in <module>
    from browsr.base import (
  File "/usr/local/lib/python3.12/site-packages/browsr/base.py", line 17, in <module>
    from upath import UPath
  File "/usr/local/lib/python3.12/site-packages/upath/__init__.py", line 2, in <module>
    from upath.core import UPath
  File "/usr/local/lib/python3.12/site-packages/upath/core.py", line 8, in <module>
    from pathlib import _PosixFlavour  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_PosixFlavour' from 'pathlib' (/usr/local/lib/python3.12/pathlib.py)

```

**Comment by juftin** [comment]
browsr doesn't officially support Python 3.12 (yet) - https://github.com/juftin/browsr/issues/34

This is coming very soon though - I expect within the next week.
